name: "02 Conditional steps"

on:
  workflow_dispatch

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: "step 1 passes"
        id: "successful_step"
        run: |
          echo "hello there from successful steps"
          exit 0
      - name: step 2 runs if step 1 was successful
        if: ${{ success() }}
        run: |
          echo "step 2 runs ..."