name: 04 workflow with user inputs

on:
  workflow_dispatch:
    inputs:
      username:
        type: string
        required: true
        default: NA
        description: Name of user
      age:
        type: number
        required: true
        default: -1
        description: Age of user

jobs:
  job_with_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Echo user name and age
        run: |
          echo "Username: ${{ inputs.username }}"
          echo "Age: ${{ inputs.age }}"
