name: 05 Checkout Action

on:
  workflow_dispatch:

jobs:
  clone-course-repo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print contents of working dir (1)
        run: ls -la ${{ github.workspace }}
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Print contents of working dir (2)
        run: ls -la ${{ github.workspace }}
      